title: "Alberto Nasi"
theme: minima
url: "https://albnasi.github.io"
baseurl: "albnasi.github"                             # "" per sito utente (username.github.io). Per project page usa "/nome-repo"

author:
  name: "Alberto Nasi"
  email: "alberto.nasi@phd.unibocconi.it"

# Plugin ufficiali supportati da GitHub Pages
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

header_pages:
  - index.md
  - Research.md
  - teaching.md
  - cv.md
  - contacts.md
